// Static demo data used when DB is not connected
// This makes the app fully functional in preview mode

export const DEMO_ROUTES = [
  {
    id: "route-1",
    name: "CBD - Rongai",
    code: "NRB-101",
    description: "Main route connecting Nairobi CBD to Rongai via Langata Road",
    origin: "Kencom (CBD)",
    destination: "Rongai Town",
    county: "Nairobi",
    isActive: true,
    color: "#10B981",
    vehicleCount: 24,
    stages: [
      { name: "Kencom", lat: -1.2864, lng: 36.8237, order: 0, isTerminal: true },
      { name: "Railways", lat: -1.2913, lng: 36.8236, order: 1, isTerminal: false },
      { name: "Nyayo Stadium", lat: -1.3044, lng: 36.8175, order: 2, isTerminal: false },
      { name: "T-Mall", lat: -1.3185, lng: 36.7977, order: 3, isTerminal: false },
      { name: "Bomas", lat: -1.3407, lng: 36.7764, order: 4, isTerminal: false },
      { name: "Rongai Town", lat: -1.3963, lng: 36.7587, order: 5, isTerminal: true },
    ],
  },
  {
    id: "route-2",
    name: "CBD - Westlands",
    code: "NRB-102",
    description: "Quick route to Westlands via Uhuru Highway and Waiyaki Way",
    origin: "Kencom (CBD)",
    destination: "Westlands",
    county: "Nairobi",
    isActive: true,
    color: "#3B82F6",
    vehicleCount: 18,
    stages: [
      { name: "Kencom", lat: -1.2864, lng: 36.8237, order: 0, isTerminal: true },
      { name: "University Way", lat: -1.2794, lng: 36.8173, order: 1, isTerminal: false },
      { name: "Museum Hill", lat: -1.2718, lng: 36.8115, order: 2, isTerminal: false },
      { name: "Westlands", lat: -1.2634, lng: 36.8029, order: 3, isTerminal: true },
    ],
  },
  {
    id: "route-3",
    name: "CBD - Thika Road",
    code: "NRB-103",
    description: "Thika Superhighway route through Roysambu and Kasarani",
    origin: "Kencom (CBD)",
    destination: "Thika Town",
    county: "Kiambu",
    isActive: true,
    color: "#F59E0B",
    vehicleCount: 32,
    stages: [
      { name: "Kencom", lat: -1.2864, lng: 36.8237, order: 0, isTerminal: true },
      { name: "Pangani", lat: -1.2685, lng: 36.8342, order: 1, isTerminal: false },
      { name: "Muthaiga", lat: -1.2533, lng: 36.8391, order: 2, isTerminal: false },
      { name: "Roysambu", lat: -1.2188, lng: 36.8732, order: 3, isTerminal: false },
      { name: "Kasarani", lat: -1.2015, lng: 36.8924, order: 4, isTerminal: false },
      { name: "Ruiru", lat: -1.1456, lng: 36.9603, order: 5, isTerminal: false },
      { name: "Thika Town", lat: -1.0396, lng: 37.0754, order: 6, isTerminal: true },
    ],
  },
  {
    id: "route-4",
    name: "CBD - Eastleigh",
    code: "NRB-104",
    description: "Route serving Eastleigh via Jogoo Road",
    origin: "Kencom (CBD)",
    destination: "Eastleigh",
    county: "Nairobi",
    isActive: true,
    color: "#EF4444",
    vehicleCount: 15,
    stages: [
      { name: "Kencom", lat: -1.2864, lng: 36.8237, order: 0, isTerminal: true },
      { name: "Muthurwa", lat: -1.2885, lng: 36.8338, order: 1, isTerminal: false },
      { name: "Eastleigh", lat: -1.2741, lng: 36.8502, order: 2, isTerminal: true },
    ],
  },
  {
    id: "route-5",
    name: "CBD - Karen",
    code: "NRB-105",
    description: "Route through Ngong Road to Karen",
    origin: "Kencom (CBD)",
    destination: "Karen",
    county: "Nairobi",
    isActive: true,
    color: "#8B5CF6",
    vehicleCount: 12,
    stages: [
      { name: "Kencom", lat: -1.2864, lng: 36.8237, order: 0, isTerminal: true },
      { name: "Ngong Road", lat: -1.3001, lng: 36.7963, order: 1, isTerminal: false },
      { name: "Prestige Plaza", lat: -1.3098, lng: 36.7856, order: 2, isTerminal: false },
      { name: "Karen", lat: -1.3222, lng: 36.7124, order: 3, isTerminal: true },
    ],
  },
  {
    id: "route-6",
    name: "Mombasa - Nyali",
    code: "MSA-201",
    description: "Cross-island route from Mombasa CBD to Nyali",
    origin: "Mombasa CBD",
    destination: "Nyali",
    county: "Mombasa",
    isActive: true,
    color: "#06B6D4",
    vehicleCount: 10,
    stages: [
      { name: "Mombasa CBD", lat: -4.0435, lng: 39.6682, order: 0, isTerminal: true },
      { name: "Nyali Bridge", lat: -4.0315, lng: 39.6823, order: 1, isTerminal: false },
      { name: "Nyali", lat: -4.0186, lng: 39.7052, order: 2, isTerminal: true },
    ],
  },
]

export const DEMO_VEHICLES = [
  {
    id: "v-1",
    plateNumber: "KCB 456J",
    nickname: "Speed Governor",
    type: "MATATU" as const,
    capacity: 14,
    isActive: true,
    isPremium: true,
    rating: 4.5,
    totalTrips: 1243,
    routes: ["CBD - Rongai"],
    imageUrl: null,
    position: { lat: -1.3185, lng: 36.7977, speed: 35, heading: 210 },
  },
  {
    id: "v-2",
    plateNumber: "KDA 789M",
    nickname: "Night Rider",
    type: "MATATU" as const,
    capacity: 14,
    isActive: true,
    isPremium: false,
    rating: 4.2,
    totalTrips: 892,
    routes: ["CBD - Westlands"],
    imageUrl: null,
    position: { lat: -1.2718, lng: 36.8115, speed: 22, heading: 320 },
  },
  {
    id: "v-3",
    plateNumber: "KBZ 123K",
    nickname: "Thika Express",
    type: "BUS" as const,
    capacity: 50,
    isActive: true,
    isPremium: true,
    rating: 4.8,
    totalTrips: 2105,
    routes: ["CBD - Thika Road"],
    imageUrl: null,
    position: { lat: -1.2188, lng: 36.8732, speed: 60, heading: 45 },
  },
  {
    id: "v-4",
    plateNumber: "KCC 321L",
    nickname: "Karen Cruiser",
    type: "MATATU" as const,
    capacity: 14,
    isActive: true,
    isPremium: false,
    rating: 3.9,
    totalTrips: 567,
    routes: ["CBD - Karen"],
    imageUrl: null,
    position: { lat: -1.3098, lng: 36.7856, speed: 18, heading: 260 },
  },
  {
    id: "v-5",
    plateNumber: "KAB 567N",
    nickname: "Mombasa Star",
    type: "BUS" as const,
    capacity: 50,
    isActive: true,
    isPremium: true,
    rating: 4.6,
    totalTrips: 1560,
    routes: ["Mombasa - Nyali"],
    imageUrl: null,
    position: { lat: -4.0315, lng: 39.6823, speed: 28, heading: 75 },
  },
  {
    id: "v-6",
    plateNumber: "KDE 890P",
    nickname: "Eastleigh Flyer",
    type: "MATATU" as const,
    capacity: 14,
    isActive: true,
    isPremium: false,
    rating: 4.0,
    totalTrips: 734,
    routes: ["CBD - Eastleigh"],
    imageUrl: null,
    position: { lat: -1.2741, lng: 36.8502, speed: 15, heading: 90 },
  },
  {
    id: "v-7",
    plateNumber: "KBC 234Q",
    nickname: "Rongai Runner",
    type: "MATATU" as const,
    capacity: 14,
    isActive: false,
    isPremium: false,
    rating: 3.7,
    totalTrips: 412,
    routes: ["CBD - Rongai"],
    imageUrl: null,
    position: null,
  },
  {
    id: "v-8",
    plateNumber: "KAA 100A",
    nickname: "Boda King",
    type: "BODA" as const,
    capacity: 1,
    isActive: true,
    isPremium: false,
    rating: 4.1,
    totalTrips: 3200,
    routes: ["CBD - Eastleigh"],
    imageUrl: null,
    position: { lat: -1.2830, lng: 36.8340, speed: 40, heading: 180 },
  },
]
